--
-- Procedure "TEST_GITHUB_PUSH"
--
CREATE OR REPLACE EDITIONABLE PROCEDURE "MY_FINANCE"."TEST_GITHUB_PUSH" 
AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('Old Line');
    DBMS_OUTPUT.PUT_LINE('2-Oct-2026 Line');
    DBMS_OUTPUT.PUT_LINE('2-Oct-2026 2nd Line');
END;
/