--
-- Table "VT1"
--
CREATE TABLE "MY_FINANCE"."VT1" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"V" VECTOR(2, FLOAT32), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/